### ISSUE TITLE
Debate necessary on Style doc

### ISSUE THREAD

**Issue by victorkane** [patio-coop/patio-homepage#3]
I just saw the un-announced and un-discussed [Style document](https://github.com/patio-coop/patio-homepage/blob/main/STYLE.md) and really feel it requires discussion.

- It seems excessive
- While there is a place for a styling guide, it is ambiguous, since on the one hand it talks about markdown, on the other about commit formats. 
- The commits, perhaps, could be more like the modern conventional semantic commits (of course we can seek some consensus on that). 
- Certainly we should exert more energy on the product than on styling until the project gets underway.

**Comment by 0cjs** [comment]
That is simply documenting what _already were the project's conventions,_ agreed upon before you joined the project. Since you're a new member joining an existing project it's normal that you're not aware of the conventions that Yasu and I are using here (and have been using for years on various projects). However, when you join an existing project, it's incumbent on you to realize that you may not know or understand the project culture and all its conventions and so you should ask about them, especially before making changes to existing things.

For disputes like this, it's important to remember that even though the disagreement might be over something seemingly trivial, it may also be surfacing because of a much deeper problem in project culture or interactions that is very important to address.

I'll close this because 1) as we agreed earlier, it's better to have all documentation relating to the project in the repo itself, rather than GitHub's proprietary issues database, 2) we have available to us far more efficient communications media (voice and text chat) for discussing this, and 3) bringing our interpersonal arguments to a public issues database for the world to see is not really a good look for the project. That said, if you strongly disagree with this decision, do re-open this issue.
