### ISSUE TITLE
“Get in touch” form doesn't work

### ISSUE THREAD

**Issue by kaat** [patio-coop/patio-homepage#52]
Hello,

I'm trying to contact you via the site's “Get in touch” form, but it shows a 405 message after sending the form via POST. It doesn't look like an expected behavior.

**Comment by kaat** [comment]
Update: the form works on https://patio.coop/, but it doesn't work on https://patio-coop.github.io/

It still appears to be an issue, because I have got a link to https://patio-coop.github.io/ first. Another link I have found in the source code of the page.

**Comment by yugawara** [comment]
Oh no and thank you for letting us know!!!!  Let me see!!!  In the mean time, if you would like to speak immediately, my personal contact (and there are many more of us in the federation) information is here:  https://tng.coop/Thank you Yuliy!!-YasuOn Mar 11, 2023, at 01:00, Yuliy Lobarev ***@***.***> wrote:﻿
Hello,
I'm trying to contact you via the site's “Get in touch” form, but it shows a 405 message after sending the form via POST. It doesn't look like an expected behavior.

**Comment by kaat** [comment]
Kudo san, thank you! My message from https://patio.coop/ seems to go through the web form, so I'm not in a hurry.

**Comment by ventolinmx** [comment]
Thanks for reporting. https://patio-coop.github.io doesn't have the form back-end. It only works on https://patio.coop
